package com.generator.mapper;

import com.generator.pojo.SysScoring;
import com.generator.pojo.SysScoringExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysScoringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int countByExample(SysScoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int deleteByExample(SysScoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int insert(SysScoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int insertSelective(SysScoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    List<SysScoring> selectByExample(SysScoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    SysScoring selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysScoring record, @Param("example") SysScoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysScoring record, @Param("example") SysScoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysScoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scoring
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysScoring record);
}