package com.generator.mapper;

import com.generator.pojo.SysTeam;
import com.generator.pojo.SysTeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int countByExample(SysTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int deleteByExample(SysTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int insert(SysTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int insertSelective(SysTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    List<SysTeam> selectByExample(SysTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    SysTeam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysTeam record, @Param("example") SysTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysTeam record, @Param("example") SysTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_team
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTeam record);
}