package com.generator.pojo;

import java.util.Date;

public class SysClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.calss_name
     *
     * @mbggenerated
     */
    private String calssName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.Class_position
     *
     * @mbggenerated
     */
    private String classPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_class.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.id
     *
     * @return the value of sys_class.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.id
     *
     * @param id the value for sys_class.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.uuid
     *
     * @return the value of sys_class.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.uuid
     *
     * @param uuid the value for sys_class.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.create_time
     *
     * @return the value of sys_class.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.create_time
     *
     * @param createTime the value for sys_class.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.delete_time
     *
     * @return the value of sys_class.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.delete_time
     *
     * @param deleteTime the value for sys_class.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.is_deleted
     *
     * @return the value of sys_class.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.is_deleted
     *
     * @param isDeleted the value for sys_class.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.calss_name
     *
     * @return the value of sys_class.calss_name
     *
     * @mbggenerated
     */
    public String getCalssName() {
        return calssName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.calss_name
     *
     * @param calssName the value for sys_class.calss_name
     *
     * @mbggenerated
     */
    public void setCalssName(String calssName) {
        this.calssName = calssName == null ? null : calssName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.Class_position
     *
     * @return the value of sys_class.Class_position
     *
     * @mbggenerated
     */
    public String getClassPosition() {
        return classPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.Class_position
     *
     * @param classPosition the value for sys_class.Class_position
     *
     * @mbggenerated
     */
    public void setClassPosition(String classPosition) {
        this.classPosition = classPosition == null ? null : classPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.bak1
     *
     * @return the value of sys_class.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.bak1
     *
     * @param bak1 the value for sys_class.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.bak2
     *
     * @return the value of sys_class.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.bak2
     *
     * @param bak2 the value for sys_class.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_class.bak3
     *
     * @return the value of sys_class.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_class.bak3
     *
     * @param bak3 the value for sys_class.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}