package com.generator.pojo;

import java.util.Date;

public class SysScoring {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.Scoring_number
     *
     * @mbggenerated
     */
    private Long scoringNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.due_to
     *
     * @mbggenerated
     */
    private String dueTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scoring.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.id
     *
     * @return the value of sys_scoring.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.id
     *
     * @param id the value for sys_scoring.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.uuid
     *
     * @return the value of sys_scoring.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.uuid
     *
     * @param uuid the value for sys_scoring.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.create_time
     *
     * @return the value of sys_scoring.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.create_time
     *
     * @param createTime the value for sys_scoring.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.delete_time
     *
     * @return the value of sys_scoring.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.delete_time
     *
     * @param deleteTime the value for sys_scoring.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.is_deleted
     *
     * @return the value of sys_scoring.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.is_deleted
     *
     * @param isDeleted the value for sys_scoring.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.user_id
     *
     * @return the value of sys_scoring.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.user_id
     *
     * @param userId the value for sys_scoring.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.Scoring_number
     *
     * @return the value of sys_scoring.Scoring_number
     *
     * @mbggenerated
     */
    public Long getScoringNumber() {
        return scoringNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.Scoring_number
     *
     * @param scoringNumber the value for sys_scoring.Scoring_number
     *
     * @mbggenerated
     */
    public void setScoringNumber(Long scoringNumber) {
        this.scoringNumber = scoringNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.due_to
     *
     * @return the value of sys_scoring.due_to
     *
     * @mbggenerated
     */
    public String getDueTo() {
        return dueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.due_to
     *
     * @param dueTo the value for sys_scoring.due_to
     *
     * @mbggenerated
     */
    public void setDueTo(String dueTo) {
        this.dueTo = dueTo == null ? null : dueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.bak1
     *
     * @return the value of sys_scoring.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.bak1
     *
     * @param bak1 the value for sys_scoring.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.bak2
     *
     * @return the value of sys_scoring.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.bak2
     *
     * @param bak2 the value for sys_scoring.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scoring.bak3
     *
     * @return the value of sys_scoring.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scoring.bak3
     *
     * @param bak3 the value for sys_scoring.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}