package com.generator.pojo;

import java.util.Date;

public class SysTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.team_name
     *
     * @mbggenerated
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.team_position
     *
     * @mbggenerated
     */
    private String teamPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.team_behave
     *
     * @mbggenerated
     */
    private Integer teamBehave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_team.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.id
     *
     * @return the value of sys_team.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.id
     *
     * @param id the value for sys_team.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.uuid
     *
     * @return the value of sys_team.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.uuid
     *
     * @param uuid the value for sys_team.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.create_time
     *
     * @return the value of sys_team.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.create_time
     *
     * @param createTime the value for sys_team.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.delete_time
     *
     * @return the value of sys_team.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.delete_time
     *
     * @param deleteTime the value for sys_team.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.is_deleted
     *
     * @return the value of sys_team.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.is_deleted
     *
     * @param isDeleted the value for sys_team.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.team_name
     *
     * @return the value of sys_team.team_name
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.team_name
     *
     * @param teamName the value for sys_team.team_name
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.team_position
     *
     * @return the value of sys_team.team_position
     *
     * @mbggenerated
     */
    public String getTeamPosition() {
        return teamPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.team_position
     *
     * @param teamPosition the value for sys_team.team_position
     *
     * @mbggenerated
     */
    public void setTeamPosition(String teamPosition) {
        this.teamPosition = teamPosition == null ? null : teamPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.team_behave
     *
     * @return the value of sys_team.team_behave
     *
     * @mbggenerated
     */
    public Integer getTeamBehave() {
        return teamBehave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.team_behave
     *
     * @param teamBehave the value for sys_team.team_behave
     *
     * @mbggenerated
     */
    public void setTeamBehave(Integer teamBehave) {
        this.teamBehave = teamBehave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.bak1
     *
     * @return the value of sys_team.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.bak1
     *
     * @param bak1 the value for sys_team.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.bak2
     *
     * @return the value of sys_team.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.bak2
     *
     * @param bak2 the value for sys_team.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_team.bak3
     *
     * @return the value of sys_team.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_team.bak3
     *
     * @param bak3 the value for sys_team.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}