package com.generator.pojo;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_studentid
     *
     * @mbggenerated
     */
    private String userStudentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.calss_id
     *
     * @mbggenerated
     */
    private Long calssId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.uuid
     *
     * @return the value of sys_user.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.uuid
     *
     * @param uuid the value for sys_user.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.delete_time
     *
     * @return the value of sys_user.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.delete_time
     *
     * @param deleteTime the value for sys_user.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_deleted
     *
     * @return the value of sys_user.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_deleted
     *
     * @param isDeleted the value for sys_user.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_studentid
     *
     * @return the value of sys_user.user_studentid
     *
     * @mbggenerated
     */
    public String getUserStudentid() {
        return userStudentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_studentid
     *
     * @param userStudentid the value for sys_user.user_studentid
     *
     * @mbggenerated
     */
    public void setUserStudentid(String userStudentid) {
        this.userStudentid = userStudentid == null ? null : userStudentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.team_id
     *
     * @return the value of sys_user.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.team_id
     *
     * @param teamId the value for sys_user.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.calss_id
     *
     * @return the value of sys_user.calss_id
     *
     * @mbggenerated
     */
    public Long getCalssId() {
        return calssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.calss_id
     *
     * @param calssId the value for sys_user.calss_id
     *
     * @mbggenerated
     */
    public void setCalssId(Long calssId) {
        this.calssId = calssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.bak1
     *
     * @return the value of sys_user.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.bak1
     *
     * @param bak1 the value for sys_user.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.bak2
     *
     * @return the value of sys_user.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.bak2
     *
     * @param bak2 the value for sys_user.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.bak3
     *
     * @return the value of sys_user.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.bak3
     *
     * @param bak3 the value for sys_user.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}